settings:
  name: NetApp Replication
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: NetApp Replication docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about NetApp Replication
          url: /concept-replication.html
        - title: Log in to NetApp Replication
          url: /task-login-replication.html
        - title: Set up data replication
          url: /task-replicating-data.html
    - title: Manage data replication
      url: /task-managing-replication.html
    - title: Learn more
      entries:
        - title: Learn about replication policies
          url: /concept-replication-policies.html
        - title: Learn about backup policies
          url: /concept-backup-policies.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: NetApp Data Services
  repo: data-services-family

